export class Constant{
  // public static CONTENT_HELP_EN="The way to find the cure you. Need and the method of getting it is very simple. The program itself will guide you.  <br><br>"
  //                             + "1.- Finding the remedy needed: From the screen 'remedies' you can access a list of remedies in alphabetical order. Sometimes, the program will help to realize the nature of their remedies. <br><br>"
  //                             + "2.- Obtaining remedy. Once you have selected the appropriate remedy, and it is displayed, you can place the phone next to a glass or bottle of water. Click 'start' to start the process. When the time has elapsed, the application indicates that the process is over and that you already have. Of your choice. <br><br>"
  //                             + "3.- How to take the remedy: The most effective way to take the remedy ready to go drinking water is sparingly with some frequency : more frequent sips the more acute is the symptom. It should decrease the frequency as the symptom recedes . The most common frequency for treating almost all symptoms is three or four times daily . In the event that the symptom is very high or very persistent it can be taken every hour , spacing the shots as the symptom recedes . More important is the frequency with which takes the amount ingested with every sip are made.In case they are remedies which are indicated , how to take them is alternating between the two ones. <br><br>"
  //                             + "4.- When stop taking remedy? When symptoms are fully dissapeared. If the sympton is too cronic or very old is better to take the remedy 1 or 2 timnes a day during some months included. no tratarse de sustancia química, there are no risk to take 'too many' amount of remedy.&lt;br&gt;*Doses does not interfere with age, or taking any medical treatment simultaneously or if you are pregnant."

  // public static CONTENT_ABOUT_EN="The current state of technology can transmit the quantum properties of almost any substance from a telephone terminal to another medium, in this case water. <br><br>"
  //                             + "Each being (plant, animal ...) has a quantum structure that identificates itself.Each component of our cells, every metabolic reaction that occurs in our body has its own quantum structure. Even a simple thought influences the bioelectrical nervous system structure. The electromagnetic signals are language communication between atoms and molecules. The tissue cells have an electric potential that generates an electromagnetic field. Communication between cells of various living tissue is performed by a system of waves. Each tissue has its own rhythm wave, which in turn determines the wave rhythm of the body to which it belongs. When for whatever reason, this intercellular electromagnetic field is altered intercellular communication is also altered and ensuing dysfunction, dysfunction we perceive through diferntes symptoms. The water, previously exposed to molecular system is capable of harmonizing the intracellular to be absorbed by the human body.Thereby, there are a synchronous resonance with the cells that make biological tissues and their functions are regulated generates electromagnetic fields. <br><br>"
  //                             + "With this application becomes available to the user the ability to have anytime , anywhere remedy your homeopathic physician has prescribed . And beyond : they can obtain means to relieve minor ailments without any advice from a professional , such as insect bites, minor headaches , dizziness by shuttle vehicles, menstrual discomfort ... Given the way to get the remedy , we must scoring an added under implementation: the ecological factor . Indeed , not the usual manufacturing waste generated conventional medicine , there is no packaging , no cardboard , or transport the product. Therefore we invite you to try this revolutionary technology and enjoy the advantages in obtaining homeopathic remedies."

  // public static CONTENT_LEGY_EN="The therapeutic posibilities inside this app does not replce in no way at professional doctors, pharmaceutical or medical.  <br><br>"
  //                             +"Anyway we hope the content of the app you have would be beneficial and useful for you, your family and friends. The content info in this app does not create any contract or agreement between you and the owners of the app.  <br><br>"
  //                             +"The use of this information in any case will have other purpose than that provided for and advised by the program authors . The use you make of the program is his sole responsibility.  <br><br>"
  //                             +"The publication of the information contained in 'Homeophone VIP' would contravene the laws of the country or jurisdiction from where access to information. The laws of your country or jurisdiction may not protect or allow the same kinds of speech or distribution of the application. 'Homeophone VIP' does not promote the violation of any law. If you need specific advice (doctor or pharmacist) , please get help from a professional who is licensed and knowledgeable in the field. <br><br>"
  //                             +"'Homeophone VIP' it is not a medical office. HomeoPhone not responsible for any problems arising from the proper or improper use of this details.If you are a minor , talk to their parents or legal guardians before use of 'Homeophone VIP'."


  // public static CONTENT_HELP_SP="La forma de encontrar el remedio que Ud. necesita y el método de obtenerlo es muy sencillo."
  //                             + "El propio programa le irá guiando. <br><br>"
  //                             + "1.- Cómo localizar el remedio que se necesita: Desde la pantalla de 'remedios' usted puede acceder  a un listado de remedios ordenados alfabéticamente. Una vez finalizado el proceso, se le indicará a preparar el remedio que va a aliviar su malestar.<br><br>"
  //                             + "2.- Obtención del remedio. Una vez que Ud. ha seleccionado el remedio correspondiente, y éste aparece en pantalla, hay que colocar el teléfono al lado de un vaso o botella de agua. Pulse en 'comenzar' para iniciar el proceso. Cuando haya transcurrido el tiempo necesario, la aplicación indicará que el proceso ha terminado y que ya dispone Ud. de su remedio.En el caso de que su síntoma precise dos remedios, deberán prepararse por separado y en vasos o botellas diferentes. <br><br>"
  //                             + "3.- Toma del remedio. La forma más eficaz de tomar el remedio ya preparado en el agua es ir bebiendo pocas cantidades con una cierta frecuencia: más frecuentes los sorbos cuanto más agudo sea el síntoma. Conviene disminuir la frecuencia a medida que el síntoma va cediendo. La frecuencia más común para el tratamiento de casi todos los síntomas es de tres o cuatro veces al día. En el caso de que el síntoma sea muy agudo o muy persistente puede tomarse cada hora, espaciando las tomas a medida que el síntoma va cediendo. Es más importante la frecuencia con la que se hacen las tomas que la cantidad ingerida con cada sorbo.En el caso de que sean los remedios los que estén indicados, la forma de tomarlos es alternando entre los dos. <br><br>"
  //                             + "4.- ¿Cuándo dejar de tomar el remedio? Cuando los síntomas hayan desaparecido por completo. Si el síntoma de que se trata es muy crónico o muy antiguo es conveniente tomarlo 1 o 2 veces al día durante incluso varios meses.*Al no tratarse de sustancia química, no existe riesgo de tomar 'demasiada' cantidad de remedio.*La dosis no varía con la edad, ni si se toma cualquier medicación convencional, o con el embarazo."

  // public static CONTENT_ABOUT_SP="El estado actual de la tecnología permite transmitir las propiedades cuánticas de casi cualquier sustancia desde un terminal de telefonía hasta otro medio, en nuestro caso el agua.<br><br>"
  //                             + "Cada ser (planta, animal...) tiene una estructura cuántica que le identifica.Cada componente de nuestras células, cada reacción metabólica que ocurre en nuestro organismo tiene su propia estructura  cuántica. Hasta un simple pensamiento influye  en la estructura bioeléctrica del Sistema Nervioso. Las señales electromagnéticas constituyen el idioma de la comunicación entre los átomos y las moléculas. Las células de los tejidos tienen un potencial eléctrico que genera un campo electromagnético. La comunicación entre las células de los diversos tejidos vivos se realiza por un sistema de ondas. Cada tejido tiene un ritmo ondulatorio propio, que a su vez condiciona el ritmo ondulatorio del órgano del que forma parte. Cuando por la razón que fuere, este campo electromagnético intercelular se altera, la comunicación intercelular se altera también y sobreviene la disfunción, disfunción que percibimos a través de diferntes síntomas. El agua, expuesta previamente al ordenamiento molecular, es capaz de armonizar los campos electromagnéticos intracelulares al ser absorbida por el cuerpo humano.De este modo se genera una resonancia sincrónica con las células que componen los tejidos biológicos y se regulan sus funciones. <br><br>"
  //                             + "Con ésta aplicación se pone al alcance del usuario la posibilidad de tener en cualquier momento y en cualquier lugar el remedio que su Médico Homeópata le haya prescrito. Y más allá: se pueden obtener medios para aliviar malestares menores sin mediar el consejo de un profesional, por ejemplo, picaduras de insectos, cefaleas leves, mareos por traslado en vehículos, molestias menstruales... Dada la forma de obtener el remedio, debemos anotar una virtud añadida a la aplicación: el factor ecológico. Efectivamente, no se generan los residuos habituales de la fabricación de un medicamento convencional, no hay envases, no hay cartonaje, ni transporte del producto. Por todo ello le invitamos a probar esta revolucionaria tecnología y disfrutar de las ventajas que aporta en la obtención de remedios homeopáticos."

  // public static CONTENT_LEGY_SP="Las posibilidades terapéuticas contenidas en este programa no sustituyen en modo alguno al consejo de un profesional sanitario, médico o farmacéutico. <br><br>"
  //                             +"En cualquier caso esperamos que el contenido de la aplicación que tiene ahora en sus manos le sea provechosa, tanto para usted como para su familia. La información contenida en este programa, no crea ningún tipo de acuerdo o contrato entre usted y los propietarios o usuarios de este sitio. <br><br>"
  //                             +"La utilización de esta información en ningún caso tendrá otro propósito que el contemplado y aconsejado por los autores del programa. El uso que usted haga del programa queda exclusivamente bajo su responsabilidad. <br><br>"
  //                             +"La publicación de la información contenida en 'Homeophone VIP' podría contravenir las leyes del país o jurisdicción desde donde se accede a la información. Las leyes de su país o jurisdicción podrían no proteger o permitir las mismas clases de expresión o distribución de la aplicación. 'Homeophone VIP' no promueve la violación de ninguna ley. Si necesita asesoramiento específico (médico o farmacéutico), por favor solicite la ayuda de un profesional que cuente con licencia y con conocimientos en la materia.<br><br>"
  //                             +"'Homeophone VIP' no es un consultorio médico.Homeophone VIP no se hace responsable de los inconvenientes que se deriven de la utilización propia o impropia de esta información.Si es menor de edad, consulte a sus progenitores o tutores legales antes de hacer uso de 'Homeophone VIP'."


  public static CONTENT_HELP_EN="If you need any help with the operation of the app, send an email from the button INFORMATION> CONTACT and fill in the attached form. You can also send us an email to info@arcagua.es and we will attend you immediately. Thank you."

  public static CONTENT_ABOUT_EN="Omeos VIP is a tool for storing and remembering, agenda style, the correctly written Latin name of the proposed homeopathic remedies and their corresponding dilutions."

  public static CONTENT_LEGY_EN="We hope that the content of the application you have now in your hands will be useful for both you and your family. The information contained in this program does not create any type of agreement or contract between you and the owners or users of this site.<br><br>"
                              +"The use of this information will not have any purpose other than that contemplated and advised by the authors of the program. Your use of the program is solely at your own risk.<br><br>"



  public static CONTENT_HELP_SP="Si necesita cualquier tipo de ayuda con el funcionamiento de la app, envíe un correo desde el botón INFORMACIÓN>CONTACTO y rellene el formulario adjunto.Tambien puede enviarnos un correo a info@arcagua.es y le atenderemos de manera inmediata. Muchas gracias."

  public static CONTENT_ABOUT_SP="Omeos VIP es una herramieta para almacenar y recordar, estilo agenda, el nombre en latín correctamente escrito de los remedios homeopáticos propuestos y sus diluciones correspondientes"

  public static CONTENT_LEGY_SP="Esperamos que el contenido de la aplicación que tiene ahora en sus manos le sea provechosa, tanto para usted como para su familia. La información contenida en este programa, no crea ningún tipo de acuerdo o contrato entre usted y los propietarios o usuarios de este sitio. <br><br>"
                              +"La utilización de esta información en ningún caso tendrá otro propósito que el contemplado y aconsejado por los autores del programa. El uso que usted haga del programa queda exclusivamente bajo su responsabilidad. <br><br>"


}
